{
 "title": "Rocket League DashBoard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Tendance par ordre décroissant",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  FOV_DESC AS \"time\",\n  FOV_DESC,\n  Distance_DESC,\n  Height_DESC,\n  Angle_DESC\nFROM rocket_cam_settings_desc_6\nORDER BY FOV_DESC"
    }
   ]
  },
  {
   "title": "FOV",
   "type": "bargauge",
   "description": "Tendance de la valeur  à la distance par les joueurs . ",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(A_FOV,$__interval),\n  sum(A_FOV) AS \"Other\"\nFROM rocket_cam_settings\nWHERE\n  FOV < 110\nGROUP BY 1\nORDER BY $__timeGroup(A_FOV,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(A_FOV,$__interval),\n  FOV AS metric,\n  sum(A_FOV) AS \"A_Distance\"\nFROM rocket_cam_settings\nWHERE\n  FOV = 110\nGROUP BY 1,2\nORDER BY $__timeGroup(A_FOV,$__interval)"
    }
   ]
  },
  {
   "title": "Distance",
   "type": "bargauge",
   "description": "Tendance de la valeur  à la distance par les joueurs . ",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(A_Distance,$__interval),\n  Distance AS metric,\n  sum(A_Distance)\nFROM rocket_cam_settings\nWHERE\n  Distance = 260\nGROUP BY 1,2\nORDER BY $__timeGroup(A_Distance,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(A_Distance,$__interval),\n  Distance AS metric,\n  sum(A_Distance)\nFROM rocket_cam_settings\nWHERE\n  Distance = 270\nGROUP BY 1,2\nORDER BY $__timeGroup(A_Distance,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(A_Distance,$__interval),\n  Distance AS metric,\n  sum(A_Distance)\nFROM rocket_cam_settings\nWHERE\n  Distance = 280\nGROUP BY 1,2\nORDER BY $__timeGroup(A_Distance,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(A_Distance,$__interval),\n  sum(A_Distance) AS \"Other\"\nFROM rocket_cam_settings\nWHERE\n  Distance IN  ( 250 , 300, 240,290,230,330,310,320,220,190 ) \nGROUP BY 1\nORDER BY $__timeGroup(A_Distance,$__interval)"
    }
   ]
  },
  {
   "title": "Height",
   "type": "bargauge",
   "description": "Tendance de la valeur  à la distance par les joueurs . ",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(A_Height,$__interval),\n  Height AS metric,\n  sum(A_Height) AS \"A_Distance\"\nFROM rocket_cam_settings\nWHERE\n  Height = 90\nGROUP BY 1,2\nORDER BY $__timeGroup(A_Height,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(A_Height,$__interval),\n  Height AS metric,\n  sum(A_Height) AS \"A_Distance\"\nFROM rocket_cam_settings\nWHERE\n  Height = 100\nGROUP BY 1,2\nORDER BY $__timeGroup(A_Height,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(A_Height,$__interval),\n  Height AS metric,\n  sum(A_Height) AS \"A_Distance\"\nFROM rocket_cam_settings\nWHERE\n  Height = 110\nGROUP BY 1,2\nORDER BY $__timeGroup(A_Height,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(A_Height,$__interval),\n  sum(A_Height) AS \"Other\"\nFROM rocket_cam_settings\nWHERE\n  Height IN ( 130 , 120 , 140 , 80 , 150 , 108 ) \nGROUP BY 1\nORDER BY $__timeGroup(A_Height,$__interval)"
    }
   ]
  },
  {
   "title": "Angle",
   "type": "bargauge",
   "description": "Tendance de la valeur  à la distance par les joueurs . ",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(A_Angle,$__interval),\n  Angle AS metric,\n  sum(A_Angle) AS \"A_Angle\"\nFROM rocket_cam_settings\nWHERE\n  Angle = -3\nGROUP BY 1,2\nORDER BY $__timeGroup(A_Angle,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(A_Angle,$__interval),\n  Angle AS metric,\n  sum(A_Angle) AS \"A_Angle\"\nFROM rocket_cam_settings\nWHERE\n  Angle = -4\nGROUP BY 1,2\nORDER BY $__timeGroup(A_Angle,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(A_Angle,$__interval),\n  Angle AS metric,\n  sum(A_Angle) AS \"A_Angle\"\nFROM rocket_cam_settings\nWHERE\n  Angle = -5\nGROUP BY 1,2\nORDER BY $__timeGroup(A_Angle,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(A_Angle,$__interval),\n  sum(A_Angle) AS \"Other\"\nFROM rocket_cam_settings\nWHERE\n  Angle IN (-1 ,-2, -6, -8, -7)\nGROUP BY 1\nORDER BY $__timeGroup(A_Angle,$__interval)"
    }
   ]
  },
  {
   "title": "Ball Cam Switch",
   "type": "bargauge",
   "description": "Tendance de la valeur  à la distance par les joueurs . ",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(Player,$__interval),\n  Ball_Camera AS metric,\n  count(Player) /4.50 AS \"Ball_Camera\"\nFROM rocket_cam_settings\nGROUP BY 1,2\nORDER BY $__timeGroup(Player,$__interval)"
    }
   ]
  }
 ]
}